package com.kleinsamuel.game.model.items;

/**
 * Created by sam on 31.05.17.
 */

public enum ItemEnum {

    KEY_GRAY,
    POTION_HEALTH,

    ARMOR_BLOOD_TORSO,
    ARMOR_BLOOD_HELMET,
    ARMOR_BLOOD_LEGS,
    ARMOR_BLOOD_FOOT_LEFT,
    ARMOR_BLOOD_FOOT_RIGHT,
    ARMOR_BLOOD_HAND_LEFT,
    ARMOR_BLOOD_HAND_RIGHT,

    ARMOR_CHAIN_TORSO,
    ARMOR_CHAIN_HELMET,
    ARMOR_CHAIN_LEGS,
    ARMOR_CHAIN_FOOT_LEFT,
    ARMOR_CHAIN_FOOT_RIGHT,
    ARMOR_CHAIN_HAND_LEFT,
    ARMOR_CHAIN_HAND_RIGHT,

    ARMOR_CLOTH_TORSO,
    ARMOR_CLOTH_HELMET,
    ARMOR_CLOTH_LEGS,
    ARMOR_CLOTH_FOOT_LEFT,
    ARMOR_CLOTH_FOOT_RIGHT,
    ARMOR_CLOTH_HAND_LEFT,
    ARMOR_CLOTH_HAND_RIGHT,

    ARMOR_GOLD_TORSO,
    ARMOR_GOLD_HELMET,
    ARMOR_GOLD_LEGS,
    ARMOR_GOLD_FOOT_LEFT,
    ARMOR_GOLD_FOOT_RIGHT,
    ARMOR_GOLD_HAND_LEFT,
    ARMOR_GOLD_HAND_RIGHT,

    ARMOR_LEATHER_TORSO,
    ARMOR_LEATHER_HELMET,
    ARMOR_LEATHER_LEGS,
    ARMOR_LEATHER_FOOT_LEFT,
    ARMOR_LEATHER_FOOT_RIGHT,
    ARMOR_LEATHER_HAND_LEFT,
    ARMOR_LEATHER_HAND_RIGHT,

    ARMOR_MYSTIC_TORSO,
    ARMOR_MYSTIC_HELMET,
    ARMOR_MYSTIC_LEGS,
    ARMOR_MYSTIC_FOOT_LEFT,
    ARMOR_MYSTIC_FOOT_RIGHT,
    ARMOR_MYSTIC_HAND_LEFT,
    ARMOR_MYSTIC_HAND_RIGHT,

    ARMOR_PLATE_TORSO,
    ARMOR_PLATE_HELMET,
    ARMOR_PLATE_LEGS,
    ARMOR_PLATE_FOOT_LEFT,
    ARMOR_PLATE_FOOT_RIGHT,
    ARMOR_PLATE_HAND_LEFT,
    ARMOR_PLATE_HAND_RIGHT,

    ARMOR_ROYAL_TORSO,
    ARMOR_ROYAL_HELMET,
    ARMOR_ROYAL_LEGS,
    ARMOR_ROYAL_FOOT_LEFT,
    ARMOR_ROYAL_FOOT_RIGHT,
    ARMOR_ROYAL_HAND_LEFT,
    ARMOR_ROYAL_HAND_RIGHT,

    ARMOR_STUDDED_TORSO,
    ARMOR_STUDDED_HELMET,
    ARMOR_STUDDED_LEGS,
    ARMOR_STUDDED_FOOT_LEFT,
    ARMOR_STUDDED_FOOT_RIGHT,
    ARMOR_STUDDED_HAND_LEFT,
    ARMOR_STUDDED_HAND_RIGHT,

    ARMOR_WILD_TORSO,
    ARMOR_WILD_HELMET,
    ARMOR_WILD_LEGS,
    ARMOR_WILD_FOOT_LEFT,
    ARMOR_WILD_FOOT_RIGHT,
    ARMOR_WILD_HAND_LEFT,
    ARMOR_WILD_HAND_RIGHT;

}
