package com.kleinsamuel.game.model.entities.npcs;

/**
 * Created by sam on 02.06.17.
 */

public enum NPCEnum {

    /*
        ANIMALS
     */

    BUTTERFLY_SMALL_RED,
    BUTTERFLY_SMAlL_BLACK,
    BUTTERFLY_SMALL_WHITE,

    BUG_SMALL_RED,
    BUG_SMALL_GREEN,
    BUG_SMALL_PURPLE,
    BUG_BIG_RED,
    BUG_BIG_GREEN,
    BUG_BIG_PURPLE,

    CROW_SMALL_BLACK,
    CROW_SMALL_BROWN,
    CROW_SMALL_WHITE,

    FROG_SMALL_BLUE,
    FROG_SMALL_BROWN,
    FROG_SMALL_GREEN,

    RAT_SMALL_BLACK,
    RAT_SMALL_BROWN,
    RAT_SMALL_GREY,
    RAT_SMALL_WHITE,
    RAT_BIG_BLACK,
    RAT_BIG_BROWN,
    RAT_BIG_GREY,
    RAT_BIG_WHITE,

    SNAKE_SMALL_GREEN,
    SNAKE_BIG_GREEN,

    SPIDER_SMALL_BLACK,
    SPIDER_SMALL_BROWN,
    SPIDER_SMALL_PURPLE,
    SPIDER_BIG_BLACK,
    SPIDER_BIG_BROWN,
    SPIDER_BIG_PURPLE,

    WOLF_SMALL_BLACK,
    WOLF_SMALL_BROWN,
    WOLF_SMALL_DARKBLACK,
    WOLF_SMALL_WHITE,

    WORM_SMALL_BROWN,
    WORM_BIG_BROWN,

    /*
        HUMANOID
     */

    GOBLIN_SMALL_GREEN_LIGHT,
    GOBLIN_SMALL_GREEN_HEAVY,

    HUMAN_KNIGHT_SMALL_METAL;

}
